version: '3'
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /home/leobarrientos/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /home/leobarrientos/mosquitto/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
      - /home/leobarrientos/mosquitto/log:/mosquitto/log:rw
      - /home/leobarrientos/mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"